### ISSUE TITLE
How to see the secret?

### ISSUE THREAD

**Issue by anthosz** [ilijamt/vht#2]
Hello,

Is it possible to see the secrets also with vht?

Indeed, when I try to use it (kv store), I can see only the path.
Example:
$ ./vht search -r /backend/metadata -k ".*c"
/backend/metadata/a/b/c
(and others metadatas)

Seems probably due to the facts that metadata path is used with kv. Do you have a workaround to see also the secrets?

Best regards,

**Comment by anthosz** [comment]
If I try with vht search -r /backend/data -k ".*c" -> 
Code: 405. Errors:

* 1 error occurred:
        * unsupported operation

**Comment by ilijamt** [comment]
@anthosz what version of Vault are you using?

**Comment by anthosz** [comment]
@ilijamt 
The last version:
version | "1.3.3"

**Comment by ilijamt** [comment]
@anthosz can you try now I fixed it so it can distinguish between version 1 and version 2 of the kv store. 

check this part of the readme now https://github.com/ilijamt/vht#example

**Comment by anthosz** [comment]
@ilijamt It works!

Thank you!
